USE [master]
GO

/****** Object:  Database [CustomerReg] ******/
DROP DATABASE [CustomerReg]
GO

/****** Object:  Database [CustomerReg] ******/
CREATE DATABASE [CustomerReg]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CustomerReg', FILENAME = N'.\MSSQL14.SQLEXPRESS\MSSQL\DATA\CustomerReg.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CustomerReg_log', FILENAME = N'.\MSSQL14.SQLEXPRESS\MSSQL\DATA\CustomerReg_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CustomerReg].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CustomerReg] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CustomerReg] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CustomerReg] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CustomerReg] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CustomerReg] SET ARITHABORT OFF 
GO

ALTER DATABASE [CustomerReg] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CustomerReg] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CustomerReg] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CustomerReg] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CustomerReg] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CustomerReg] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CustomerReg] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CustomerReg] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CustomerReg] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CustomerReg] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CustomerReg] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CustomerReg] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CustomerReg] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CustomerReg] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CustomerReg] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CustomerReg] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CustomerReg] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CustomerReg] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CustomerReg] SET  MULTI_USER 
GO

ALTER DATABASE [CustomerReg] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CustomerReg] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CustomerReg] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CustomerReg] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CustomerReg] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CustomerReg] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CustomerReg] SET  READ_WRITE 
GO

USE [CustomerReg]
GO

/****** Object:  Table [dbo].[CustomerDetails] ******/
DROP TABLE [dbo].[CustomerDetails]
GO

/****** Object:  Table [dbo].[CustomerDetails] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CustomerDetails](
	[CustomerId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NULL,
	[Surname] [varchar](50) NULL,
	[PolicyReference] [varchar](9) NULL,
	[DateOfBirth] [datetime] NULL,
	[EmailAddress] [varchar](150) NULL
) ON [PRIMARY]
GO